In [109]:
import pandas as pd
import numpy as np

In [110]:
dataset = pd.read_csv("Concrete Strength.csv")

In [111]:
dataset.columns

Index(['Cement (component 1)(kg in a m^3 mixture)',
       'Blast Furnace Slag (component 2)(kg in a m^3 mixture)',
       'Fly Ash (component 3)(kg in a m^3 mixture)',
       'Water  (component 4)(kg in a m^3 mixture)',
       'Superplasticizer (component 5)(kg in a m^3 mixture)',
       'Coarse Aggregate  (component 6)(kg in a m^3 mixture)',
       'Fine Aggregate (component 7)(kg in a m^3 mixture)', 'Age (day)',
       'Concrete compressive strength(MPa, megapascals) '],
      dtype='object')

In [112]:
independent = dataset[['Cement (component 1)(kg in a m^3 mixture)',
       'Blast Furnace Slag (component 2)(kg in a m^3 mixture)',
       'Fly Ash (component 3)(kg in a m^3 mixture)',
       'Water  (component 4)(kg in a m^3 mixture)',
       'Superplasticizer (component 5)(kg in a m^3 mixture)',
       'Coarse Aggregate  (component 6)(kg in a m^3 mixture)',
       'Fine Aggregate (component 7)(kg in a m^3 mixture)', 'Age (day)']]

In [113]:
dependent = dataset[['Concrete compressive strength(MPa, megapascals) ']]

In [114]:
independent

Cement (component 1)(kg in a m^3 mixture)  \
0                                         540.0   
1                                         540.0   
2                                         332.5   
3                                         332.5   
4                                         198.6   
...                                         ...   
1025                                      276.4   
1026                                      322.2   
1027                                      148.5   
1028                                      159.1   
1029                                      260.9   

      Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
0                                                   0.0       
1                                                   0.0       
2                                                 142.5       
3                                                 142.5       
4                                                 132.4       
...                                                 ...       
1025                                              116.0       
1026                                                0.0       
1027                                              139.4       
1028                                              186.7       
1029                                              100.5       

      Fly Ash (component 3)(kg in a m^3 mixture)  \
0                                            0.0   
1                                            0.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
...                                          ...   
1025                                        90.3   
1026                                       115.6   
1027                                       108.6   
1028                                         0.0   
1029                                        78.3   

      Water  (component 4)(kg in a m^3 mixture)  \
0                                         162.0   
1                                         162.0   
2                                         228.0   
3                                         228.0   
4                                         192.0   
...                                         ...   
1025                                      179.6   
1026                                      196.0   
1027                                      192.7   
1028                                      175.6   
1029                                      200.6   

      Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                                   2.5     
1                                                   2.5     
2                                                   0.0     
3                                                   0.0     
4                                                   0.0     
...                                                 ...     
1025                                                8.9     
1026                                               10.4     
1027                                                6.1     
1028                                               11.3     
1029                                                8.6     

      Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
0                                                1040.0      
1                                                1055.0      
2                                                 932.0      
3                                                 932.0      
4                                                 978.4      
...                                                 ...      
1025                                              870.1      
1026                                              817.9      
1027                                              892.4      
1028                                         

In [115]:
dependent

Concrete compressive strength(MPa, megapascals) 
0                                                79.99
1                                                61.89
2                                                40.27
3                                                41.05
4                                                44.30
...                                                ...
1025                                             44.28
1026                                             31.18
1027                                             23.70
1028                                             32.77
1029                                             32.40

[1030 rows x 1 columns]

In [116]:
from sklearn.model_selection import train_test_split

In [167]:
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,train_size = 0.90, random_state = 0)

In [168]:
x_train

Cement (component 1)(kg in a m^3 mixture)  \
957                                      143.0   
267                                      212.0   
863                                      288.0   
342                                      297.2   
416                                      213.5   
..                                         ...   
277                                      251.4   
763                                      385.0   
835                                      144.0   
559                                      239.6   
684                                      192.0   

     Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
957                                              169.4       
267                                                0.0       
863                                              121.0       
342                                                0.0       
416                                                0.0       
..                                                 ...       
277                                                0.0       
763                                                0.0       
835                                                0.0       
559                                              359.4       
684                                              288.0       

     Fly Ash (component 3)(kg in a m^3 mixture)  \
957                                       142.7   
267                                       124.8   
863                                         0.0   
342                                       117.5   
416                                       174.2   
..                                          ...   
277                                       118.3   
763                                         0.0   
835                                       175.0   
559                                         0.0   
684                                         0.0   

     Water  (component 4)(kg in a m^3 mixture)  \
957                                      190.7   
267                                      159.0   
863                                      177.0   
342                                      174.8   
416                                      159.2   
..                                         ...   
277                                      188.5   
763                                      186.0   
835                                      158.0   
559                                      185.7   
684                                      192.0   

     Superplasticizer (component 5)(kg in a m^3 mixture)  \
957                                                8.4     
267                                                7.8     
863                                                7.0     
342                                                9.5     
416                                               11.7     
..                                                 ...     
277                                                5.8     
763                                                0.0     
835                                               18.0     
559                                                0.0     
684                                                0.0     

     Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
957                                              967.4      
267                                             1085.4      
863                                              908.0      
342                                             1022.8      
416                                             1043.6      
..                                                 ...      
277                                             1028.4      
763                                              966.0      
835                                              943.0      
559                                              941.6      
684                                              929.

In [169]:
#from sklearn.preprocessing import StandardScaler
#sc=StandardScaler()
#x_train=sc.fit_transform(x_train)#transformation of x_train using StandardScaler
#x_test=sc.transform(x_test)

In [170]:
#x_train

In [171]:
#from sklearn.svm import SVR
#regressor=SVR(C=7000000.0)
#regressor.fit(x_train,y_train) #to train the model

In [182]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [194]:
weight = regressor.coef_

In [195]:
weight

array([[ 0.12060184,  0.1080986 ,  0.08966115, -0.13554582,  0.35264901,
         0.02365182,  0.02204194,  0.11202835]])

In [196]:
bais = regressor.intercept_

In [197]:
bais

array([-33.72422679])

In [200]:
ypred = regressor.predict(x_test)

In [201]:
ypred

array([[39.92361304],
       [14.4404402 ],
       [61.37360548],
       [53.51863976],
       [24.37589014],
       [54.08312209],
       [46.27319441],
       [26.99303228],
       [53.31377422],
       [37.70159565],
       [16.87364662],
       [39.0192799 ],
       [29.43361435],
       [35.72916248],
       [48.07750418],
       [56.71284856],
       [35.36552721],
       [29.39800568],
       [48.85553712],
       [35.06688632],
       [53.43326734],
       [32.15282136],
       [32.46410615],
       [48.4074237 ],
       [23.71585531],
       [23.60172988],
       [70.00103038],
       [26.36733032],
       [56.71284856],
       [48.20458424],
       [18.98507356],
       [36.67054526],
       [17.58093143],
       [20.19816296],
       [24.77142985],
       [15.26968836],
       [53.63500868],
       [27.70303205],
       [27.33260738],
       [25.87414885],
       [52.71055984],
       [30.6495324 ],
       [26.12768979],
       [35.15116348],
       [53.50954966],
       [54

In [202]:
from sklearn.metrics import r2_score

In [203]:
r_score = r2_score(y_test,ypred)

In [204]:
r_score

0.6130673777738749

In [205]:
import pickle

In [206]:
my_model = ("concrete strength predic.sav")

In [208]:
pickle.dump(regressor,open(my_model,'wb'))